spring.application.name=everymilestonerentals

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/everymilestonerentals
spring.datasource.username=postgres
spring.datasource.password=Gamecube1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true